# Generated by Django 5.2.7 on 2026-01-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='name',
        ),
    ]
