# Generated by Django 5.2.7 on 2026-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_rename_patient_name_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
