# Generated by Django 5.2.7 on 2026-01-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointment_available_from_appointment_available_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='available_to',
        ),
    ]
