# Generated by Django 5.2.7 on 2026-01-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_remove_appointment_available_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='user',
        ),
    ]
