# Generated by Django 5.2.7 on 2026-01-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_rename_doctor_appointment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
