# Generated by Django 5.2.7 on 2026-01-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
