# Generated by Django 5.2.7 on 2026-01-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date',
        ),
    ]
