# Generated by Django 5.2.7 on 2026-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_remove_doctor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
