# Generated by Django 5.2.7 on 2026-01-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_doctor_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
