# Generated by Django 5.2.7 on 2026-01-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_to',
        ),
    ]
