# Generated by Django 5.2.7 on 2026-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0008_remove_doctor_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.TextField(blank=True, help_text='One per line'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.TextField(blank=True, help_text='One per line'),
        ),
    ]
