# Generated by Django 5.2.7 on 2026-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_doctoravailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
