# Generated by Django 5.2.7 on 2026-01-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0012_doctoravailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
