# Generated by Django 5.2.7 on 2026-01-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0014_doctoravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='user',
            new_name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day', 'available_from', 'available_to')},
        ),
    ]
