# Generated by Django 5.2.7 on 2026-01-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0015_rename_user_doctoravailability_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
